<?php

use Drupal\node\NodeInterface;
use \Drupal\Core\Session\AccountInterface;

function apigee_api_product_catalog_productowners_node_access_records(NodeInterface $node)
{
  $grants = [];
  if ($node->getType() == 'api_product') {
    /* @var $owner \Drupal\Core\Field\Plugin\Field\FieldType\EmailItem */
    $tags_to_invalidate = [];
    foreach ($node->get("field_product_owners") as $owner) {
      $tags_to_invalidate[] = "apigee_api_product_catalog_productowners:{$owner->getString()}";
      $product_owner = user_load_by_mail(strtolower($owner->getString()));
      if ($product_owner !== FALSE) {
        $grants[] = array(
          'realm' => 'apigee_api_product_catalog_productowner',
          'gid' => $product_owner->id(),
          'grant_view' => 1,
          'grant_update' => 1,
          'grant_delete' => 0
        );
      }
    }
    \Drupal\Core\Cache\Cache::invalidateTags($tags_to_invalidate);
  } else if ($node->getType() == 'apidoc') {
    $nids = Drupal::entityQuery('node')
      ->condition('type', 'api_product')
      ->condition('field_api_doc', $node->id())
      ->execute();
    foreach(\Drupal\node\Entity\Node::loadMultiple($nids) as $product_node) {
      $grants+=apigee_api_product_catalog_productowners_node_access_records($product_node);
    }
  }
  return $grants;
}

function apigee_api_product_catalog_productowners_node_grants(AccountInterface $account, $op)
{
  $grants = [];
  if ($account->id()) {
    $grants['apigee_api_product_catalog_productowner'] = [
      $account->id(),
    ];
  }
  return $grants;
}


function apigee_api_product_catalog_productowners_form_sm_appdashboard_apigee_appdetails_edit_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $allowed_products = \Drupal\apigee_api_product_catalog_productowners\AppsDashboardStorageService::getProductsToAdminister();
  foreach($form['details__api_products']['app_credentials'] as &$credential) {
    foreach($credential['apiproduct'] as $key => &$value) {
      if(!in_array($key, $allowed_products)) {
        $value['#disabled'] = TRUE;
      }
    }
  }
}
