<?php
/**
 * Copyright 2020 Google LLC
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Return the realm string to use for a particular role.
 *
 * @param $role
 *
 * @return string
 */
function apigee_api_product_catalog_audience_roles_realm($role) {
  return "apigee_api_product_catalog_audience_roles:$role";
}

/**
 * @param NodeInterface $node
 *
 * @return array
 */
function apigee_api_product_catalog_audience_roles_node_access_records(NodeInterface $node) {
  $grants = [];
  if ($node->getType() == 'api_product') {
    /* @var $role Drupal\Core\Field\Plugin\Field\FieldType\StringItem */
    foreach ($node->get("field_audience_roles") as $role) {
      $grants[] = [
        'realm' => apigee_api_product_catalog_audience_roles_realm($role->getString()),
        'gid' => 1,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
      ];
    }
  }
  else {
    if ($node->getType() == 'apidoc') {
      $nids = Drupal::entityQuery('node')
        ->condition('type', 'api_product')
        ->condition('field_api_doc', $node->id())
        ->execute();
      foreach (\Drupal\node\Entity\Node::loadMultiple($nids) as $product_node) {
        $grants += apigee_api_product_catalog_audience_roles_node_access_records($product_node);
      }
    }
  }
  return $grants;
}

/**
 * @param AccountInterface $account
 * @param $op
 *
 * @return array
 */
function apigee_api_product_catalog_audience_roles_node_grants(AccountInterface $account, $op) {
  $grants = [];
  if ($account->id()) {
    foreach ($account->getRoles() as $role) {
      $grants[apigee_api_product_catalog_audience_roles_realm($role)] = [1];
    }
  }
  else {
    $grants[apigee_api_product_catalog_audience_roles_realm(AccountInterface::ANONYMOUS_ROLE)] = [1];
  }
  return $grants;
}

/**
 * Implements hook_FORM_ID_form_alter
 *
 * Default the value of the RBAC field in edge.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function apigee_api_product_catalog_audience_roles_form_apigee_edge_api_product_access_control_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['rbac']['attribute_name']['#default_value'] = 'DRUPAL_RBAC';
  $form['rbac']['attribute_name']['#attributes']['readonly'] = 'readonly';
  $form['#submit'][] = 'apigee_api_product_catalog_audience_roles_form_apigee_edge_api_product_access_control_form_submit';
}

/**
 * When the settings form is updated generate the API Product json file and
 * trigger feeds import
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @throws \Exception
 */
function apigee_api_product_catalog_audience_roles_form_apigee_edge_api_product_access_control_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state) {
  apigee_api_product_catalog_cron();
  $fids = Drupal::entityQuery('feeds_feed')
    ->condition('type', 'api_product_json_importer')
    ->execute();
  /* @var $feed \Drupal\feeds\FeedInterface*/
  foreach(\Drupal\feeds\Entity\Feed::loadMultiple($fids) as $feed) {
    $feed->startBatchImport();
  }
}